// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2-s4Wv0U0xxJ_K4bqLEm_ff10eZt25wU',
    appId: '1:463798038207:web:c0fc911f224c10eefda00a',
    messagingSenderId: '463798038207',
    projectId: 'researchmantraofficial-80bcf',
    authDomain: 'researchmantraofficial-80bcf.firebaseapp.com',
    storageBucket: 'researchmantraofficial-80bcf.firebasestorage.app',
    measurementId: 'G-7G3ZLHMDM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGG6_5zLOmMwxZfXUwBCd7ahHg1Gb2cqM',
    appId: '1:463798038207:android:5c7498727ae297a6fda00a',
    messagingSenderId: '463798038207',
    projectId: 'researchmantraofficial-80bcf',
    storageBucket: 'researchmantraofficial-80bcf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaOdywbPRwVKhr_uwLjk6IkqcdIttefrc',
    appId: '1:463798038207:ios:3373bf5c6fdfbc63fda00a',
    messagingSenderId: '463798038207',
    projectId: 'researchmantraofficial-80bcf',
    storageBucket: 'researchmantraofficial-80bcf.firebasestorage.app',
    iosBundleId: 'com.researchMantraOfficial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaOdywbPRwVKhr_uwLjk6IkqcdIttefrc',
    appId: '1:463798038207:ios:c235e22cb0d8200afda00a',
    messagingSenderId: '463798038207',
    projectId: 'researchmantraofficial-80bcf',
    storageBucket: 'researchmantraofficial-80bcf.firebasestorage.app',
    iosBundleId: 'com.example.researchMantraOfficial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2-s4Wv0U0xxJ_K4bqLEm_ff10eZt25wU',
    appId: '1:463798038207:web:3224dd2488fb8a57fda00a',
    messagingSenderId: '463798038207',
    projectId: 'researchmantraofficial-80bcf',
    authDomain: 'researchmantraofficial-80bcf.firebaseapp.com',
    storageBucket: 'researchmantraofficial-80bcf.firebasestorage.app',
    measurementId: 'G-GJQD8M3MZC',
  );

}